{{- if and .Values.podDisruptionBudget.enabled (gt (int .Values.replicaCount) 1) -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "spotalis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spotalis.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "spotalis.selectorLabels" . | nindent 6 }}
{{- end }}
