{{- if .Values.webhook.enabled -}}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "spotalis.fullname" . }}-mutating-webhook
  labels:
    {{- include "spotalis.labels" . | nindent 4 }}
  annotations:
    {{- if and .Values.webhook.certManager.enabled (not .Values.webhook.tls.existingSecret) }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "spotalis.fullname" . }}-webhook-cert
    {{- end }}
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
webhooks:
- name: pod.spotalis.io
  admissionReviewVersions: ["v1"]
  clientConfig:
    service:
      name: {{ include "spotalis.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1-pod
      port: {{ .Values.service.webhookPort }}
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  sideEffects: None
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE"]
    resources: ["pods"]
    scope: "*"
  namespaceSelector:
    matchExpressions:
    - key: spotalis.io/enabled
      operator: In
      values: ["true"]
{{- end }}
